export const HOME_PAGE_LINK = '/'
export const SCAN_CAR_LINK = '/scan-plate'
export const LOGIN_LINK = '/login'
export const REPORT_LINK = '/statistics'
export const SCAN_RESULT = '/list'
export const SCAN_RESULT_DETAIL = '/detail'
export const LOGOUT_LINK = '/logout'
export const ADD_CAR_LINK = '/add-car'
